name: The Coach
favicon: null
layout_spectrum: 0.2603916961234063
typography_spectrum: 0.8823531412053853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6524101721588522
  lightness: 0.10101527557708323
  saturation: 0.44719935883767903
  rhythmicContrast: 0.8514311800245196
purpose: []
